version: '3'

networks:
  yii:


services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    ports:
      - "8081:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - mysql
    networks:
      - yii

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - yii

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=mysql
       - PMA_USER=root
       - PMA_PASSWORD=1
    networks:
      - yii
    depends_on:
      - mysql

